"""empty message

Revision ID: 195fee23467a
Revises: d940b0b8e144
Create Date: 2023-01-31 14:06:24.961530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195fee23467a'
down_revision = 'd940b0b8e144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_uid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_uid')
    # ### end Alembic commands ###
